# =======================================================
#                       Statements
# =======================================================
<statement> ::= <if_statement> |
                <block> |
                <while_loop> |
                <for_loop> |
                <for_Each_loop> |
                <switch> |
                <assignment> |
                <data_type> |
                <elif_clause> |
                <else> |
                <break_statement> |
                <continue_statement> |
                <return_statement> |
                <function>

<block> ::= "{" <statement>* "}"

# =======================================================
#                       Data Types
# =======================================================
<data_type> ::= "string" |
                "i32" |
                "i64" |
                "f32" |
                "f64" |
                "bool" |
                <data_type> "[]"

# ======================================================
#                      Unary Operator
# ======================================================
<post_fix> ::= <identifier> ("--" | "++")
<pre_fix> ::= ("--" | "++" ) <identifier>

# =======================================================
#                       Variables
# =======================================================
<identifier> ::= [a-zA-Z_][a-zA-Z0-9_]*
<declaration> ::= <data_type> <identifier> "=" <expression> ";"
<assignment> ::= <identifier> "=" <expression> ";" |
                <identifier> "[" <expression> "]" "=" <expression> ";"

# =======================================================
#                      if-statements
# =======================================================
<if_statement> ::= "if" "(" <expression> ")" ":" "then" (<statement> | <block>) "done" ";" |
                    "if" "(" <expression> ")" ":" "then" "{"
                        <statement>*
                    "}"
                    <elif_clause>*
                    <else>?
                    "fi" ";"

<elif_clause> ::= "elif" "(" <expression> ")" ":" "then" "{"
                    <expression>*
                    "}"

<else> ::= "else" "{"
                <expression>*
            "}"

# =======================================================
#                       Loops
# =======================================================
<for_loop> ::= "for" "(" <for_header> ")" ":" "do" "{"
                    <statement>*
                "}" "done" ";"

<for_header> ::= <data_type> <identifier> "=" <expression> ";"
                <expression> ";"
                <for_update>

<for_update> ::= <identifier> "++" |
                <identifier> "--" |
                <identifier> "=" <expression>

<for_Each_loop> ::= "for" "(" <data_type> <identifier> ":" <identifier> ")"  ":" "do" "{"
                        <statement>*
                    "}" "done" ";"

<while_loop> ::= "while" "(" <expression> ")" ":" "do" "{"
                    <statement>*
                "}" "done" ";"

# ========================================================
#               Switch Statement
# ========================================================
<switch> ::= "switch" "(" <expression> ")" ":" "do" "{"
                <case_clause>+
            "}" "done" ";"

<case_clause> ::= "case" "(" <case_values> ")" "{"
                    <statement>*
                "}"

<case_values> ::= <literal> |
                <literal> ("|" <literal> )* |
                "*"

# =========================================================
#                       Flow control
# =========================================================
<break_statement> ::= "break" ";"
<continue_statement> ::= "continue" ";"
<return_statement> ::= "return" ";" |
                        "return" <expression> ";"

# =========================================================
#                       Print statements
#==========================================================
<print_statement> ::= "print" "(" <expression> ")" ";" |
                    "printf" "(" <string_literal> ")" ";"

# =========================================================
#                       Literals
# =========================================================
<literal> ::= <number_literal> |
                <string_literal> |
                <boolean_literal>

<boolean_literal> ::= "true" | "false"
<number_literal> ::= [0-9]+ | [0-9]+ "." [0-9]+ ["d" | "f"]?
<string_literal> ::= '"' [^"]* '"'

# =========================================================
#                       Functions
# =========================================================
<access_modifier> ::= "public" |
                    "protected" |
                    "private"

<function> ::= <access_modifier> <identifier> "( <function_form> )" "->" ("null" | <data_type> ) "{"
                <statement>*
            "}" "done" ";"

<function_form> ::= <data_type> <identifier> | "void"
<return_type> ::= ("null" | <data_type>) | <data_type>

# =========================================================
#                       Classes
# =========================================================


# =========================================================
#                       Comments
# =========================================================
# Single-line comments:
# 1: // comment text
# 2: # comment text

# Multi-line comments :
# 1: /* comment text */

# Documentation comments - docs related only:
# 1: /** documentation text */

# Examples:
# // This is a comment
# # This is also a comment
# /* This is a
#    multi-line comment */
# /** This documents a function */

# ==============================================================
#            Arithmetic Operators and Logical Operators
# ==============================================================